controller_list:
  - name: fake_robot_left_controller
    type: $(arg fake_execution_type)
    joints:
      - left_arm_joint_1
      - left_arm_joint_2
      - left_arm_joint_3
      - left_arm_joint_4
      - left_arm_joint_5
      - left_arm_joint_6
  - name: fake_robot_right_controller
    type: $(arg fake_execution_type)
    joints:
      - right_arm_joint_1
      - right_arm_joint_2
      - right_arm_joint_3
      - right_arm_joint_4
      - right_arm_joint_5
      - right_arm_joint_6
initial:  # Define initial robot poses per group
  - group: robot_left
    pose: home