<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_robot">
    <xacro:include filename="$(find my_robot_urdf)/urdf/workbench.xacro" />
    <xacro:include filename="$(find my_robot_urdf)/urdf/arm.xacro" />
    <xacro:include filename="$(find my_robot_urdf)/urdf/arm_coco.xacro" />
    <xacro:include filename="$(find my_robot_urdf)/urdf/arm_yuzi.xacro" />

    
    <!-- Define parameters for workbench 1-->
    <xacro:property name="workbench_height_1" value="0.1" />
    <xacro:property name="workbench_length_1" value="2" />
    <xacro:property name="workbench_width_1" value="5" />
    <xacro:property name="workbench_name_1" value="main_workbench" />

    <xacro:property name="workbench_height_2" value="0.6" />
    <xacro:property name="workbench_length_2" value="2" />
    <xacro:property name="workbench_width_2" value="5" />
    <xacro:property name="workbench_name_2" value="main_workbench_2" />

    <!-- Instantiate the workbench 1 as the root link -->
    <xacro:workbench workbench_name="${workbench_name_1}" workbench_height="${workbench_height_1}" workbench_length="${workbench_length_1}" workbench_width="${workbench_width_1}" />
    <xacro:workbench workbench_name="${workbench_name_2}" workbench_height="${workbench_height_2}" workbench_length="${workbench_length_2}" workbench_width="${workbench_width_2}" />

    <!-- Main body link (central base link) -->
    <link name="central_base_link">
        <origin xyz="0 0 1.5" rpy="0 0 0" /> <!-- Adjusted to be above the workbench -->
    </link>

    <!-- Connect each workbench to the central base link with a fixed joint -->
    <joint name="base_to_workbench_1_joint" type="fixed">
        <parent link="central_base_link"/>
        <child link="${workbench_name_1}"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <joint name="base_to_workbench_2_joint" type="fixed">
        <parent link="central_base_link"/>
        <child link="${workbench_name_2}"/>
        <origin xyz="${workbench_width_1/2} 0 0" rpy="0 0 0"/>
    </joint>

    <!-- Instantiate the arms, attaching it to the central base link -->
    <xacro:arm prefix="alex_" parent_link="central_base_link" xyz="0 0 ${workbench_height_1}" rpy="0 0 0" />
    <xacro:arm_coco prefix="coco_" parent_link="central_base_link" xyz="0 1 ${workbench_height_1}" rpy="0 0 0" />
    <xacro:arm_yuzi prefix="yuzi_" parent_link="central_base_link" xyz="0 2 ${workbench_height_1}" rpy="0 0 0" />
</robot>