<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:macro name="workbench_ground" params="workbench_name workbench_height=1.0 workbench_length=2 workbench_width=2">
        <link name="${workbench_name}">
            <inertial>
                <origin xyz="0 0 ${workbench_height / 2}" rpy="0 0 0"/>
                <mass value="1000.0"/>
                <inertia ixx="100" ixy="0" ixz="0" iyy="100" iyz="0" izz="100"/>
            </inertial>
            <visual>
                <origin xyz="0 0 ${workbench_height / 2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${workbench_length} ${workbench_width} ${workbench_height}"/>
                </geometry>
                <material name="light_grey">
                    <color rgba="0.7 0.7 0.7 1"/> <!-- White grey color -->
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 ${workbench_height / 2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${workbench_length} ${workbench_width} ${workbench_height}"/>
                </geometry>
            </collision>
        </link>
    </xacro:macro>
</robot>
