controller_list:
  - name: fake_alex_robot_controller
    type: $(arg fake_execution_type)
    joints:
      - alex_arm_joint_1_alex
      - alex_arm_joint_2_alex
      - alex_arm_joint_3_alex
      - alex_arm_joint_4_alex
      - alex_arm_joint_5_alex
      - alex_arm_joint_6_alex
  - name: fake_yuzi_robot_controller
    type: $(arg fake_execution_type)
    joints:
      - yuzi_arm_joint_1_yuzi
      - yuzi_arm_joint_2_yuzi
      - yuzi_arm_joint_3_yuzi
      - yuzi_arm_joint_4_yuzi
      - yuzi_arm_joint_5_yuzi
      - yuzi_arm_joint_6_yuzi
  - name: fake_coco_robot_eef1_controller
    type: $(arg fake_execution_type)
    joints:
      - coco_joint_link_1_coco
      - coco_joint_link_2_coco
      - coco_joint_link_3_coco
      - coco_joint_link_4_coco
      - coco_joint_link_5_coco
      - coco_arm_joint_6_coco
  - name: fake_coco_robot_eef2_controller
    type: $(arg fake_execution_type)
    joints:
      - coco_joint_link_1_coco
      - coco_joint_link_2_coco
      - coco_joint_link_3_coco
      - coco_joint_link_4_coco
      - coco_joint_link_5_coco
      - coco_arm_joint_6_coco
  - name: fake_eef_alex_controller
    type: $(arg fake_execution_type)
    joints:
      []
  - name: fake_eef_yuzi_controller
    type: $(arg fake_execution_type)
    joints:
      []
  - name: fake_eef1_coco_controller
    type: $(arg fake_execution_type)
    joints:
      []
  - name: fake_eef2_coco_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
  - group: alex_robot
    pose: home
  - group: yuzi_robot
    pose: home
  - group: coco_robot_eef1
    pose: home