controller_list:
  - name: arm_alex_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - alex_arm_joint_1
      - alex_arm_joint_2
      - alex_arm_joint_3
      - alex_arm_joint_4
      - alex_arm_joint_5
      - alex_arm_joint_6
  - name: yuzi_robot_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - yuzi_joint_link_1_yuzi
      - yuzi_joint_link_2_yuzi
      - yuzi_joint_link_3_yuzi
      - yuzi_joint_link_4_yuzi
      - yuzi_joint_link_5_yuzi
      - yuzi_joint_link_6_yuzi
  - name: coco_robot_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - coco_joint_link_1_coco
      - coco_joint_link_2_coco
      - coco_joint_link_3_coco
      - coco_joint_link_4_coco
      - coco_joint_link_5_coco
      - coco_arm_joint_6_coco