controller_list:
  - name: alex_robot_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - alex_arm_joint_1_alex
      - alex_arm_joint_2_alex
      - alex_arm_joint_3_alex
      - alex_arm_joint_4_alex
      - alex_arm_joint_5_alex
      - alex_arm_joint_6_alex
  - name: yuzi_robot_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - yuzi_arm_joint_1_yuzi
      - yuzi_arm_joint_2_yuzi
      - yuzi_arm_joint_3_yuzi
      - yuzi_arm_joint_4_yuzi
      - yuzi_arm_joint_5_yuzi
      - yuzi_arm_joint_6_yuzi
  - name: coco_robot_eef1_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - coco_joint_link_1_coco
      - coco_joint_link_2_coco
      - coco_joint_link_3_coco
      - coco_joint_link_4_coco
      - coco_joint_link_5_coco
      - coco_arm_joint_6_coco
  - name: coco_robot_eef2_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - coco_joint_link_1_coco
      - coco_joint_link_2_coco
      - coco_joint_link_3_coco
      - coco_joint_link_4_coco
      - coco_joint_link_5_coco
      - coco_arm_joint_6_coco